services:
  
  neurohagana-database-service:

    image: yonatanmatuz/neurohagana-database-development-image:1.0

    build: ./Database

    container_name: neurohagana-database-container

    ports:
      - 3306:3306

    restart: unless-stopped

    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=neuro_hagana
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MYSQL_ROOT_PASSWORD=root
    
    # volumes:
    #   - neurohagana-db:/var/lib/mysql


  neurohagana-backend-service: 

    image: yonatanmatuz/neurohagana-backend-development-image:1.0

    build: ./Backend

    container_name: neurohagana-backend-container

    restart: unless-stopped

    ports:
      - 4000:4000

    environment:
      - MYSQL_HOST=neurohagana-database-service
      - MYSQL_DATABASE=neuro_hagana
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""

  neurohagana-frontend-service:

    image: yonatanmatuz/neurohagana-frontend-development-image:1.0

    build: ./Frontend

    container_name: neurohagana-frontend-container

    ports:
      - 3000:3000
    
    restart: unless-stopped


# volumes:
#   neurohagana-db: